# Problem 3

In [1]:
import numpy as np
import scipy.linalg 

In [2]:
k = 2.
b = 20.*12
m = 100./386
K = np.array([
    [6*k, 0.0, 0.0],
    [0.0, 6*k,-b*k],
    [0.0,-b*k, 3*k*b**2]
])
M = np.array([
    [  m, 0.0, 0.0],
    [0.0,   m, 0.0],
    [0.0, 0.0, m*b**2/6]
])
freq, shapes = scipy.linalg.eig(K,M)

In [3]:
freq

array([142.67131819+0.j,  42.60868181+0.j,  46.32      +0.j])

In [4]:
omegas = np.sqrt(freq)
omegas

array([11.94450996+0.j,  6.5275326 +0.j,  6.80587981+0.j])

In [5]:
np.around(shapes,5)

array([[ 0.     ,  0.     ,  1.     ],
       [-0.99865,  1.     ,  0.     ],
       [ 0.05193,  0.002  ,  0.     ]])